# Generated by Django 6.0.4 on 2026-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
    ]
